version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - pip install --upgrade awscli
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 977629633660.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=977629633660.dkr.ecr.eu-west-1.amazonaws.com/nilssondev
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn spring-boot:build-image
      - docker tag $REPOSITORY_URI:latest image-resizer
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - target/ImageResizer-0.0.1-SNAPSHOT.jar
    - cloudformation.yaml



