version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 977629633660.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=977629633660.dkr.ecr.eu-west-1.amazonaws.com/nilssondev
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn spring-boot:build-image
      - docker tag  image-resizer 977629633660.dkr.ecr.eu-west-1.amazonaws.com/nilssondev:latest
  post_build:
    commands:
      - docker push 977629633660.dkr.ecr.eu-west-1.amazonaws.com/nilssondev:latest
      - printf '[{"name":"image-resizer","imageUri":"%s"}]' 977629633660.dkr.ecr.eu-west-1.amazonaws.com/nilssondev:latest > imagedefinitions.json
artifacts:
  discard-paths: yes
  files:
    - imagedefinitions.json
    - target/*
    - scripts/*
    - cloudformation.yaml



