AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Internet Group For Image Resizer"
      GroupDescription: "SSH and web traffic in, all traffic out."
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:  0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  ResizerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: "ResizerInstanceProfile"
      Roles:
        - "EC2InstanceRole"
  Linux:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: "Name"
          Value: "image-resizer-server"
      IamInstanceProfile: !Ref ResizerInstanceProfile
      ImageId: ami-0ed961fa828560210
      InstanceType: t2.micro
      KeyName: ImageResizerPutty
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum -y update
          yum install -y ruby
          yum install -y aws-cli
          yum install -y java
          cd /home/ec2-user
          wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto

  ApplicationDeployment:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: "image-resizer-server"
      ComputePlatform: "Server"
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref ApplicationDeployment
      DeploymentGroupName: image-resizer-app-group
      Ec2TagFilters:
        - Key: "Name"
          Value: "image-resizer-server"
          Type: "KEY_AND_VALUE"
      ServiceRoleArn: "arn:aws:iam::977629633660:role/CodeDeployRole"
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - Linux
        - PublicIp
    Description: Server's PublicIp Address