AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Internet Group"
      GroupDescription: "SSH and web traffic in, all traffic out."
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:  0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '5000'
          ToPort: '5000'
          CidrIp: 0.0.0.0/0
  Linux:
    Type: 'AWS::EC2::Instance'
    Properties:
      IamInstanceProfile: !Ref MyInstanceProfile
      ImageId: ami-0ed961fa828560210
      InstanceType: t2.micro
      KeyName: ImageResizerPutty
      SecurityGroupIds: "MyInstanceProfile"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install java
          cd /
          sudo aws s3api get-object --bucket application-artifacts-andreas --key myapp.zip myapp.zip
          sudo unzip myapp.zip
          java -jar target/ImageResizer-0.0.1-SNAPSHOT.jar


Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - Linux
        - PublicIp
    Description: Server's PublicIp Address